version: '3.9'
services:
  app:
    image: 'ghcr.io/isaacdomini/cd-ddns-updater:main'
    restart: unless-stopped
    ports:
      - '8090:8080'
    volumes:
      - ./data:/data
networks:
  default:
    name: cdhome
