version: '3.9'

services:
  nextcloud-db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - db.env

  nextcloud-app:
    hostname: cloud.isaacdomini.com
    image: nextcloud:23-apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data/nextcloud:/opt/nextcloud/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TRUSTED_PROXIES=[10.0.0.1,10.0.0.3]
      - REDIS_HOST=nextcloud-redis
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=domcloud.ml
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.isaacdomini.com domcloud.ml
      - POSTGRES_HOST=nextcloud-db
      - NEXTCLOUD_DATA_DIR=/opt/nextcloud/data
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
      - nextcloud-cron
      - nextcloud-redis

  nextcloud-cron:
    image: nextcloud:23-apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data/nextcloud:/opt/nextcloud/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  nextcloud-db:
  nextcloud:
networks:
  default:
    name: cdhome
