version: '3.9'

services:
  nextcloud-db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    env_file:
      - db.env

  nextcloud:
    hostname: home.isaacdomini.com
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data/nextcloud:/opt/nextcloud/data
    environment:
      - POSTGRES_HOST=nextcloud-db
      - NEXTCLOUD_DATA_DIR=/opt/nextcloud/data
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
  
  collabora-code:
    ports:
      - '9980:9980'
    image: collabora/code:latest
    restart: always
    environment:
      - password=collaborapassword
      - username=collabora
      - domain=home.isaacdomini.com
      - extra_params=--o:ssl.enable=true
    env_file:
      - collabora.env
volumes:
  nextcloud-db:
  nextcloud:
networks:
  default:
    name: cdhome
